
/* SCRIPT DE CRIÇÃO DO BANCO DE DADOS, EXECUTE DE GO EM GO*/
CREATE DATABASE HOTEL
GO

USE HOTEL
/* CRIAÇÃO DE TABELAS */
CREATE TABLE CATEGORIA(
	ID_CATEGORIA INT PRIMARY KEY IDENTITY,
	CLASSE VARCHAR(12) NOT NULL,
	NOME_CATEGORIA VARCHAR(20) UNIQUE,

	CHECK (CLASSE IN('PESSOA','PRODUTO','SERVICO', 'CONTA', 'LOCAL')))
GO

CREATE TABLE PESSOA(
	ID_PESSOA INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(50) NOT NULL,
	CPF CHAR(11) UNIQUE,
	EMAIL VARCHAR(30) UNIQUE,
	DATA_NASC DATE NOT NULL,
	FK_CATEGORIA INT NOT NULL,
	SEXO CHAR(1) NOT NULL,
	TELEFONE VARCHAR(15) UNIQUE

)
GO

CREATE TABLE ENDERECO(
	ID_ENDERECO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(15) NOT NULL,
	CIDADE VARCHAR(15) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	FK_PESSOA INT NOT NULL,
)
GO

CREATE TABLE USUARIO(
	ID_USER INT PRIMARY KEY IDENTITY,
	LOGIN VARCHAR(15) UNIQUE,
	SENHA VARCHAR(16) NOT NULL,
	FK_PESSOA INT NOT NULL,
	NIVEL VARCHAR(20)
)
GO

CREATE TABLE PRODUTOS(
	ID_PRODUTO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(50) NOT NULL,
	MARCA VARCHAR(10) NOT NULL,
	FORNECEDOR VARCHAR(20) NOT NULL,
	UNI_MEDIDA VARCHAR(6) NOT NULL,
	VALIDADE DATE NOT NULL,
	ESTOQUE INT,
	VALOR MONEY NOT NULL,
	FK_CATEGORIA INT NOT NULL
)
GO

CREATE TABLE SERVICOS(
	ID_SERVICO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	DESCRICAO VARCHAR(50),
	VALOR MONEY NOT NULL,
	FK_CATEGORIA INT NOT NULL
)
GO

CREATE TABLE CONTAS(
	ID_CONTA INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	VALOR MONEY NOT NULL,
	STATUS CHAR(1) ,
	DESCRICAO VARCHAR(50),
	FK_CATEGORIA INT NOT NULL,
	FK_HOSPEDAGEM INT,

	CHECK (STATUS IN('A', 'P'))
)
GO

CREATE TABLE C_LOCAL(
	ID_C_LOCAL INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	QUANT_PESSOAS INT NOT NULL,
	VALOR MONEY NOT NULL,
	DESCONTO_MAX FLOAT
)
GO

CREATE TABLE LOCAL(
	ID_LOCAL INT PRIMARY KEY IDENTITY,
	NOME_LOCAL VARCHAR(30) NOT NULL,
	DESCRICAO VARCHAR(50),
	STATUS VARCHAR(10),
	FK_C_LOCAL INT NOT NULL,

	CHECK (STATUS IN('DESOCUPADO', 'OCUPADO'))
)
GO

CREATE TABLE HOSPEDAGEM (
	ID_HOSPEDAGEM INT PRIMARY KEY IDENTITY,
	FK_PESSOA INT NOT NULL,
	FK_LOCAL INT NOT NULL,
	STATUS VARCHAR(10),
	DATA_ENTRADA DATE NOT NULL,
	HORA_ENTRADA TIME NOT NULL,
	DATA_SAIDA DATE NOT NULL,
	HORA_SAIDA TIME NOT NULL,
	QUANT_PESSOAS INT

	CHECK (STATUS IN('RESERVADA', 'CHECKIN', 'CHECKOUT', 'CANCELADA'))
)
GO

/*QUERYS DE CONSTRAINTS DAS FOREIGN KEYS (FK)*/
-- PESSOA
ALTER TABLE PESSOA ADD CONSTRAINT FK_PESSOA_CATEGORIA
FOREIGN KEY(FK_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
GO

--ENDEREÇO
ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_PESSOA
FOREIGN KEY(FK_PESSOA) REFERENCES PESSOA(ID_PESSOA)
GO
-- USUARIO
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_PESSOA
FOREIGN KEY(FK_PESSOA) REFERENCES PESSOA(ID_PESSOA)
GO
--PRODUTOS
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRODUTOS_CATEGORIA
FOREIGN KEY(FK_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
GO
-- SERVIÇOS
ALTER TABLE SERVICOS ADD CONSTRAINT FK_SERVICOS_CATEGORIA
FOREIGN KEY(FK_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
GO
-- CONTAS
ALTER TABLE CONTAS ADD CONSTRAINT FK_CONTAS_CATEGORIA
FOREIGN KEY(FK_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
GO
ALTER TABLE CONTAS ADD CONSTRAINT FK_CONTAS_HOSPEDAGEM
FOREIGN KEY(FK_HOSPEDAGEM) REFERENCES HOSPEDAGEM(ID_HOSPEDAGEM)
GO
-- LOCAL
ALTER TABLE LOCAL ADD CONSTRAINT FK_LOCAL_C_LOCAL
FOREIGN KEY(FK_C_LOCAL) REFERENCES C_LOCAL(ID_C_LOCAL)
GO
-- HOSPEDAGEM
ALTER TABLE HOSPEDAGEM ADD CONSTRAINT FK_HOSPEDAGEM_PESSOA
FOREIGN KEY(FK_PESSOA) REFERENCES PESSOA(ID_PESSOA)
GO

-- TRIGGER CRIADA PARA ADICIONAR CONTA ASSIM QUE FOR CADASTRADO UMA RESERVA
CREATE OR ALTER TRIGGER TRG_CONTA_HOSPEDAGEM
ON DBO.HOSPEDAGEM
FOR INSERT AS
	DECLARE
		@IDHOSPEDAGEM INT, @IDLOCAL INT,  @VALOR FLOAT

	SELECT @IDHOSPEDAGEM = ID_HOSPEDAGEM FROM inserted
	SELECT @IDLOCAL = FK_LOCAL FROM inserted
	SET @VALOR = (SELECT VALOR FROM C_LOCAL WHERE ID_C_LOCAL = (SELECT FK_C_LOCAL FROM LOCAL WHERE ID_LOCAL = @IDLOCAL))

	INSERT INTO CONTAS VALUES ('PRIMEIRA CONTA',@VALOR, 'A', 'CONTA INICIAL', (SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOME_CATEGORIA = 'ENTRADA'), @IDHOSPEDAGEM )

GO

--INSERTS NA TABELA CATEGORIA
INSERT INTO CATEGORIA VALUES('CONTA', 'ENTRADA')
INSERT INTO CATEGORIA VALUES('CONTA', 'SAIDA')
INSERT INTO CATEGORIA VALUES('PESSOA', 'CLIENTE')
INSERT INTO CATEGORIA VALUES('PESSOA', 'FUNCIONARIO')
INSERT INTO CATEGORIA VALUES('PRODUTO', 'COMIDA')
INSERT INTO CATEGORIA VALUES('PRODUTO', 'BEBIDA')
INSERT INTO CATEGORIA VALUES('SERVICO', 'LIMPEZA')
INSERT INTO CATEGORIA VALUES('SERVICO', 'SPA')
GO

--INSERTS NA TABELA DE CATEGORIA DE LOCAIS
INSERT INTO C_LOCAL VALUES('SOLTEIRO', 1,99.99, 10)
INSERT INTO C_LOCAL VALUES('DUPLO', 2,149.99, 10)
INSERT INTO C_LOCAL VALUES('TRIPLO', 3,199.99, 10)
INSERT INTO C_LOCAL VALUES('VIP', 1,299.99, 10)
GO

--INSERTS NA TABELA DE LOCAL
INSERT INTO LOCAL VALUES ('101','PRIMEIRO ANDAR','DESOCUPADO',1)
INSERT INTO LOCAL VALUES ('102','PRIMEIRO ANDAR','DESOCUPADO',1)
INSERT INTO LOCAL VALUES ('203','SEGUNDO ANDAR','DESOCUPADO',2)
INSERT INTO LOCAL VALUES ('204','SEGUNDO ANDAR','DESOCUPADO',2)
INSERT INTO LOCAL VALUES ('303','TERCEIRO ANDAR','DESOCUPADO',3)
INSERT INTO LOCAL VALUES ('304','TERCEIRO ANDAR','DESOCUPADO',3)
INSERT INTO LOCAL VALUES ('401','QUARTO ANDAR','DESOCUPADO',4)
GO

--INSERTS NA TABELA DE PESSOA
INSERT INTO PESSOA VALUES ('BELTRANO', '123XXX346XX', 'BELTRANO@EMAIL.COM', '05/01/1999', 4,'M','62 4000-1111')
INSERT INTO PESSOA VALUES ('FULANO', '123XXX146XX', 'FULANO@EMAIL.COM', '05/02/1997', 3,'M','62 4000-1112')
INSERT INTO PESSOA VALUES ('SICLANO', '444XXX346XX', 'SICLANO@EMAIL.COM', '21/05/1986', 4,'M','62 4000-1113')
INSERT INTO PESSOA VALUES ('ANA', '521XXX126XX', 'ANA@EMAIL.COM', '05/05/1992', 3,'F','62 4000-1114')
INSERT INTO PESSOA VALUES ('ROBERTA', '010XXX346XX', 'ROBERTA@EMAIL.COM', '05/04/1996', 3,'F','62 4000-1115')
INSERT INTO PESSOA VALUES ('MARIA', '001XXX356XX', 'MARIA@EMAIL.COM', '21/08/1988', 3,'F','62 4000-1116')
GO

--INSERTS NA TABELA DE ENDEREÇO
INSERT INTO ENDERECO VALUES('AVENIDA 1', 'SETOR SUL', 'GOIANIA','GO',1)
INSERT INTO ENDERECO VALUES('AVENIDA 2', 'SETOR SUL', 'GOIANIA','GO',2)
INSERT INTO ENDERECO VALUES('RUA 9', 'SETOR SUL', 'GOIANIA','GO',3)
INSERT INTO ENDERECO VALUES('AVENIDA 12', 'CENTRO', 'GOIANIA','GO',4)
INSERT INTO ENDERECO VALUES('AVENIDA 61', 'SETOR NORTE', 'GOIANIA','GO',5)
INSERT INTO ENDERECO VALUES('AVENIDA 1', 'SETOR SUL', 'GOIANIA','GO',6)
GO

--INSERTS NA TABELA DE PRODUTO
INSERT INTO PRODUTOS VALUES('REFRIGERANTE', 'COCA', 'DISTRIBUIDORA VIDA', '500ML', '13/11/2023', 21, 10.00, 6)
INSERT INTO PRODUTOS VALUES('SUCO', 'COCA', 'DISTRIBUIDORA VIDA', '500ML', '13/11/2023', 21, 8.00, 6)
INSERT INTO PRODUTOS VALUES('SALGADO', 'CASEIRA', 'HOTEL', '500G', '20/12/2021', 21, 10.00, 5)
INSERT INTO PRODUTOS VALUES('COXINHA', 'CASEIRA', 'HOTEL', '500G', '2021/11/13', 21, 10.00, 6)
INSERT INTO PRODUTOS VALUES('CERVEJA', 'BREJA', 'DISTRIBUIDORA VIDA', '500ML', '2023/11/13', 21, 10.00, 6)
INSERT INTO PRODUTOS VALUES('VINHO', 'DELVALE', 'DISTRIBUIDORA VIDA', '600ML', '2023/11/13', 21, 10.00, 6)
GO
--INSERTS NA TABELA DE SERVIÇO
INSERT INTO SERVICOS VALUES('LIMPEZA QUARTO', 'LIMPEZA EXTRA COMPLETA DE QUARTO', 80.00,7)
INSERT INTO SERVICOS VALUES('LIMPEZA BANHEIRO', 'LIMPEZA EXTRA COMPLETA DE BANHEIRO', 40.00,7)
INSERT INTO SERVICOS VALUES('SAUNA', 'SAUNA', 50.00,8)
INSERT INTO SERVICOS VALUES('MASSAGEM', 'MASSAGEM COMPLETA', 60.00,8)
GO
--INSERT NA TABELA DE USUÁRIO
INSERT INTO USUARIO VALUES('ADMIN', '1234', 1,'ADMIN')
INSERT INTO USUARIO VALUES('FUNCIONARIO1','1234',2,'NIVEL1')
INSERT INTO USUARIO VALUES('FUNCIONARIO2','1234',3,'NIVEL2')
INSERT INTO USUARIO VALUES('FUNCIONARIO3','1234',4,'NIVEL3')
GO

--INSERT NA TABELA DE HOSPEDAGEM
INSERT INTO HOSPEDAGEM VALUES(1,1,'RESERVADA', '21/12/2021','10:00','28/12/2021','10:00', 1)
INSERT INTO HOSPEDAGEM VALUES(2,2,'RESERVADA', '21/12/2021','10:00','28/12/2021','10:00', 1)
INSERT INTO HOSPEDAGEM VALUES(4,7,'RESERVADA', '21/12/2021','10:00','28/12/2021','10:00', 4)
INSERT INTO HOSPEDAGEM VALUES(3,4,'RESERVADA', '21/12/2021','10:00','28/12/2021','10:00', 2)
INSERT INTO HOSPEDAGEM VALUES(5,5,'RESERVADA', '21/12/2021','10:00','28/12/2021','10:00', 2)
INSERT INTO HOSPEDAGEM VALUES(6,6,'RESERVADA', '21/12/2021','10:00','28/12/2021','10:00', 3)
GO