CREATE DATABASE HOTEL
GO

USE HOTEL
/* CRIAÇÃO DE TABELAS */
CREATE TABLE CATEGORIA(
	ID_CATEGORIA INT PRIMARY KEY IDENTITY,
	CLASSE VARCHAR(12) NOT NULL,
	NOME VARCHAR(20) NOT NULL,

	CHECK (CLASSE IN('PESSOA','PRODUTO','SERVICO', 'CONTA', 'LOCAL')))
GO

CREATE TABLE PESSOA(
	ID_PESSOA INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(50) NOT NULL,
	CPF CHAR(11) UNIQUE,
	EMAIL VARCHAR(30) UNIQUE,
	DATA_NASC DATE NOT NULL,
	FK_CATEGORIA INT NOT NULL

)
GO

CREATE TABLE TELEFONE(
	ID_TEL INT PRIMARY KEY IDENTITY,
	NUMERO VARCHAR NOT NULL,
	FK_PESSOA INT NOT NULL
)
GO

CREATE TABLE ENDERECO(
	ID_ENDERECO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(15) NOT NULL,
	CIDADE VARCHAR(15) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	FK_PESSOA INT NOT NULL,
)
GO

CREATE TABLE USUARIO(
	ID_USER INT PRIMARY KEY IDENTITY,
	LOGIN VARCHAR(15) UNIQUE,
	SENHA VARCHAR(16) NOT NULL,
	FK_PESSOA INT NOT NULL
)
GO

CREATE TABLE PRODUTOS(
	ID_PRODUTO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(50) NOT NULL,
	MARCA VARCHAR(10) NOT NULL,
	FORNECEDOR VARCHAR(20) NOT NULL,
	UNI_MEDIDA VARCHAR(6) NOT NULL,
	VALIDADE DATE NOT NULL,
	ESTOQUE INT,
	VALOR MONEY NOT NULL,
	FK_CATEGORIA INT NOT NULL
)
GO

CREATE TABLE SERVICOS(
	ID_SERVICO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	DESCRICAO VARCHAR(50),
	VALOR MONEY NOT NULL,
	FK_CATEGORIA INT NOT NULL
)
GO

CREATE TABLE CONTAS(
	ID_CONTA INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	VALOR MONEY NOT NULL,
	STATUS CHAR(1) ,
	DESCRICAO VARCHAR(50),
	FK_CATEGORIA INT NOT NULL,
	FK_HOSPEDAGEM INT,

	CHECK (STATUS IN('A', 'P'))
)
GO

CREATE TABLE C_LOCAL(
	ID_C_LOCAL INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	QUANT_PESSOAS INT NOT NULL,
	VALOR MONEY NOT NULL,
	DESCONTO_MAX FLOAT
)
GO

CREATE TABLE LOCAL(
	ID_LOCAL INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	DESCRICAO VARCHAR(50),
	STATUS VARCHAR(10),
	FK_C_LOCAL INT NOT NULL,

	CHECK (STATUS IN('DESOCUPADO', 'OCUPADO'))
)
GO

CREATE TABLE HOSPEDAGEM (
	ID_HOSPEDAGEM INT PRIMARY KEY IDENTITY,
	FK_PESSOA INT NOT NULL,
	FK_LOCAL INT NOT NULL,
	STATUS VARCHAR(10),
	DATA_ENTRADA DATE NOT NULL,
	HORA_ENTRADA TIME NOT NULL,
	DATA_SAIDA DATE NOT NULL,
	HORA_SAIDA TIME NOT NULL,
	QUANT_PESSOAS INT

	CHECK (STATUS IN('RESERVADA', 'CHECKIN', 'CHECKOUT', 'CANCELADA'))
)
GO

/*CONSTRAINTS DE FOREIGN KEYS (FK)*/
-- PESSOA
ALTER TABLE PESSOA ADD CONSTRAINT FK_PESSOA_CATEGORIA
FOREIGN KEY(FK_CATEGORIA REFERENCES CATEGORIA(ID_CATEGORIA)
GO
--TELEFONE
ALTER TABLE TELEFONE ADD CONSTRAINT FK_TELEFONE_PESSOA
FOREIGN KEY(FK_PESSOA) REFERENCES PESSOA(ID_PESSOA)
GO
--ENDEREÇO
ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_PESSOA
FOREIGN KEY(FK_PESSOA) REFERENCES PESSOA(ID_PESSOA)
GO
-- USUARIO
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_PESSOA
FOREIGN KEY(FK_PESSOA) REFERENCES PESSOA(ID_PESSOA)
GO
--PRODUTOS
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRODUTOS_CATEGORIA
FOREIGN KEY(FK_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
GO
-- SERVIÇOS
ALTER TABLE SERVICOS ADD CONSTRAINT FK_SERVICOS_CATEGORIA
FOREIGN KEY(FK_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
GO
-- CONTAS
ALTER TABLE CONTAS ADD CONSTRAINT FK_CONTAS_CATEGORIA
FOREIGN KEY(FK_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
GO
ALTER TABLE CONTAS ADD CONSTRAINT FK_CONTAS_HOSPEDAGEM
FOREIGN KEY(FK_HOSPEDAGEM) REFERENCES HOSPEDAGEM(ID_HOSPEDAGEM)
GO
-- LOCAL
ALTER TABLE LOCAL ADD CONSTRAINT FK_LOCAL_C_LOCAL
FOREIGN KEY(FK_C_LOCAL) REFERENCES C_LOCAL(ID_C_LOCAL)
GO
-- HOSPEDAGEM
ALTER TABLE HOSPEDAGEM ADD CONSTRAINT FK_HOSPEDAGEM_PESSOA
FOREIGN KEY(FK_PESSOA) REFERENCES PESSOA(ID_PESSOA)
GO




CREATE PROCEDURE

CREATE PROCEDURE CADASTRO_CLASSE @CLASSE VARCHAR(12), @NOME VARCHAR(20)
AS
	
	INSERT INTO CLASSE VALUES(@CLASSE,@NOME)
GO

CADASTRO 'PESSOA','CLIENTE' 
GO

/* FALTA RODAR */

VERIFICAR O CHECK DA CATEGORIA

CRIAR UMA PROCEDURE COM UMA VARIAVEL A MAIS PARA BUSCAR A CATEGORIA
PARA INSERIR A FK CORRESPONDENTE

CREATE PROCEDURE CLIENTES @CATEGORIA VARCHAR(12)
AS
	SELECT PESSOA, NOME,
	FROM PESSOA
	INNER JOIN TELEFONE
	ON IDPESSOA = ID_PESSOA
	WHERE TIPO = @TIPO
GO

CREATE PROCEDURE CAD_PESSOA @NOME VARCHAR(30), @SEXO CHAR(1), @NASCIMENTO DATE,
@CATEGORIA VARCHAR(12), @EMAIL VARCHAR(30), @CPF CHAR(11), @NUMERO VARCHAR(15),
@NOME_END VARCHAR(30), @BAIRRO VARCHAR(15), @CIDADE VARCHAR(15), @ESTADO CHAR(2)
AS
	DECLARE @FK_CATEGORIA INT, @FK_PESSOA INT

	SET @FK_CATEGORIA = (SELECT ID_CATEGORIA FROM CATEGORIA WHERE @CATEGORIA = NOME)

	INSERT INTO PESSOA VALUES(@NOME,@CPF,@EMAIL,@NASCIMENTO,FK_CATEGORIA,@SEXO)

	SET @FK_PESSOA = (SELECT ID_PESSOA FROM PESSOA WHERE ID_PESSOA
	= @@IDENTITY

	INSERT INTO TELEFONE VALUES(@NUMERO,@FK_PESSOA)
	INSERT INTO ENDERECO VALUES(@NOME_END,@BAIRRO,@CIDADE,@ESTADO,@FK_PESSOA)
GO


CREATE PROCEDURE CAD_USUARIO  @LOGIN VARCHAR(30), @SENHA VARCHAR(16)
AS
	DECLARE @FK_PESSOA INT

	SET @FK_PESSOA = (SELECT ID_PESSOA FROM PESSOA WHERE @LOGIN = EMAIL)

	INSERT INTO USUARIO VALUES(@LOGIN, @SENHA, @FK_PESSOA)
GO


CREATE PROCEDURE CAD_PRODUTO @NOME VARCHAR(50), @MARCA VARCHAR(10), @FORNECEDOR VARCHAR(20),
@UNI_MEDIDA VARCHAR(6), @VALIDADE DATE, @ESTOQUE INT, @VALOR MONEY, @CATEGORIA VARCHAR(12)
AS
	DECLARE @FK_CATEGORIA INT

	SET @FK_CATEGORIA = (SELECT ID_CATEGORIA FROM CATEGORIA WHERE @CATEGORIA = NOME)

	INSERT INTO PRODUTOS VALUES(@NOME, @MARCA, @FORNECEDOR, @UNI_MEDIDA, @VALIDADE, @ESTOQUE, @VALOR, @FK_CATEGORIA)
GO

CREATE PROCEDURE CAD_SERVICOS @NOME VARCHAR(30), @DESCRICAO VARCHAR(50), @VALOR MONEY, @CATEGORIA VARCHAR(12)
AS
	DECLARE @FK_CATEGORIA INT

	SET @FK_CATEGORIA = (SELECT ID_CATEGORIA FROM CATEGORIA WHERE @CATEGORIA = NOME)

	INSERT INTO SERVICOS VALUES(@NOME, @DESCRICAO, @VALOR, @FK_CATEGORIA)
GO

CREATE PROCEDURE CAD_CONTAS @NOME VARCHAR(30), @VALOR MONEY, @STATUS CHAR(1), @DESCRICAO VARCHAR(50), @CATEGORIA VARCHAR(12)
AS
	DECLARE FK_CATEGORIA INT,  FK_HOSPEDAGEM INT

	SET

CREATE PROCEDURE CAD_C_LOCAL @NOME VARCHAR(30), @QUANT_PESSOAS INT, @VALOR MONEY, @DESCONTO_MAX
AS
	INSERT INTO C_LOCAL VALUES(@NOME, @QUANT_PESSOAS, @VALOR, @DESCONTO_MAX)
GO	


CREATE PROCEDURE CAD_LOCAL @NOME VARCHAR(30), @DESCRICAO VARCHAR(50), @STATUS VARCHAR(10),@CATEGORIA VARCHAR(30)
AS 
	DECLARE @FK_C_LOCAL INT

	SET @FK_C_LOCAL = (SELECT ID_C_LOCAL FROM C_LOCAL WHERE @CATEGORIA = NOME)

	INSERT INTO LOCAL VALUES(@NOME, @DESCRICAO, @STATUS, @FK_C_LOCAL)
GO

CREATE PROCEDURE CAD_HOSPEDAGEM @LOCAL VARCHAR(30), @CPF CHAR(11), @STATUS VARCHAR(10), @DATA_ENTRADA DATE, @HORA_ENTRADA TIME, @DATA_SAIDA DATE, @HORA_SAIDA TIME, @QUANT_PESSOAS INT
AS
	DECLARE @FK_LOCAL INT, @FK_PESSOA INT

	SET @FK_LOCAL = (SELECT ID_LOCAL FROM LOCAL WHERE @LOCAL = NOME)
	SET @FK_PESSOA = (SELECT CPF FROM PESSOA WHERE @CPF = CPF)

	INSERT INTO HOSPEDAGEM VALUES(@FK_PESSOA,@FK_LOCAL,@STATUS,@DATA_ENTRADA,@HORA_ENTRADA, @DATA_SAIDA, @HORA_SAIDA,@QUANT_PESSOAS)
GO

CREATE PROCEDURE CAD_CONTA @NOME VARCHAR(30), @VALOR MONEY, @STATUS CHAR(1), @DESCRICAO VARCHAR(50), @CATEGORIA VARCHAR(20), @CPF CHAR(11)
AS
	DECLARE FK_CATEGORIA INT, FK_HOSPEDAGEM INT

	SET @FK_CATEGORIA = (SELECT ID_CATEGORIA FROM CATEGORIA WHERE @CATEGORIA = NOME)
	SET @FK_HOSPEDAGEM = (SELECT ID_HOSPEDAGEM FROM HOSPEDAGEM WHERE @CPF = CPF)

	INSERT INTO CONTAS VALUES(@NOME, @VALOR, @STATUS, @DESCRICAO, @FK_CATEGORIA, @FK_HOSPEDAGEM)
GO


CREATE PROCEDURE VIEW_PESSOA @TIPO INT
AS
	IF TIPO = 1
	SELECT P.NOME, P.CPF, P.SEXO, P.EMAIL, P.DATA_NASC AS IDADE, C.NOME AS CATEGORIA, T.NUMERO, E.ESTADO
	FROM PESSOA P
	INNER JOIN CATEGORIA C ON P.FK_CATEGORIA = C.ID_CATEGORIA
	INNER JOIN TELEFONE T ON T.FK_PESSOA = P.ID_PESSOA
	INNER JOIN ENDERECO E ON E.FK_PESSOA = P.ID_PESSOA
	ELSE
	SELECT P.NOME, P.CPF, P.SEXO, P.EMAIL, P.DATA_NASC AS IDADE, C.NOME AS CATEGORIA, T.NUMERO, E.NOME AS LOGRADOURO, E.BAIRRO, E.CIDADE, E.ESTADO
	FROM PESSOA P
	INNER JOIN CATEGORIA C ON P.FK_CATEGORIA = C.ID_CATEGORIA
	INNER JOIN TELEFONE T ON T.FK_PESSOA = P.ID_PESSOA
	INNER JOIN ENDERECO E ON E.FK_PESSOA = P.ID_PESSOA
GO

CREATE PROCEDURE VIEW_LOCAL
AS
	SELECT L.NOME, L.DESCRICAO, L.STATUS, C.NOME, C.VALOR
	FROM LOCAL L
	INNER JOIN C_LOCAL C ON L.FK_C_LOCAL = C.ID_C_LOCAL
GO

CREATE PROCEDURE VIEW_CONTAS
AS
	SELECT C.NOME, C.VALOR, C.STATUS, C.DESCRICAO, CA.NOME, P.NOME
	FROM CONTAS C
	INNER JOIN CATEGORIA CA ON CA.ID_CATEGORIA = C.FK_CATEGORIA
	INNER JOIN HOSPEDAGEM H ON H.ID_HOSPEDAGEM = C.FK_HOSPEDAGEM
	INNER JOIN PESSOA P ON P.ID_PESSOA = H.FK_PESSOA
GO


CREATE PROCEDURE VIEW_HOSPEDAGEM @TIPO INT
AS
	IF @TIPO = 1
	SELECT H.ID_HOSPEDAGEM, P.NOME , L.NOME AS 'LOCAL', H.STATUS, H.DATA_ENTRADA, H.DATA_SAIDA, H.QUANT_PESSOAS
	FROM HOSPEDAGEM H
	INNER JOIN PESSOA P ON P.ID_PESSOA = H.FK_PESSOA
	INNER JOIN LOCAL L ON L.ID_LOCAL = H.FK_LOCAL
	ELSE
	SELECT H.ID_HOSPEDAGEM, P.NOME, P.CPF, L.NOME AS 'LOCAL', H.STATUS, H.DATA_ENTRADA,H.HORA_ENTRADA, H.DATA_SAIDA, H.HORA_SAIDA, H.QUANT_PESSOAS
	FROM HOSPEDAGEM H
	INNER JOIN PESSOA P ON P.ID_PESSOA = H.FK_PESSOA
	INNER JOIN LOCAL L ON L.ID_LOCAL = H.FK_LOCAL
GO


--UTEIS
SP_COLUMNS 'NOME TABELA'
GO

SP_HELP 'NOME TABELA'
GO

ACRESCENTADOS:
ALTER TABLE PESSOA 
ADD TELEFONE INT;

ALTER TABLE USUARIO
ADD NIVEL VARCHAR(20);

SELECT ID_PRODUTO, NOME , MARCA, FORNECEDOR, UNI_MEDIDA, VALIDADE, ESTOQUE, VALOR, FK_CATEGORIA FROM PRODUTOS

SELECT P.ID_PRODUTO, P.NOME , P.MARCA, P.FORNECEDOR, P.UNI_MEDIDA, P.VALIDADE, P.ESTOQUE, P.VALOR, C.NOME
FROM PRODUTOS P
INNER JOIN CATEGORIA C ON 

SELECT ID_PRODUTO, NOME , MARCA, FORNECEDOR, UNI_MEDIDA, VALIDADE, ESTOQUE, VALOR, ID_CATEGORIA
FROM PRODUTOS 
INNER JOIN CATEGORIA  ON FK_CATEGORIA = ID_CATEGORIA

SELECT P.ID_PRODUTO, P.NOME , P.MARCA, P.FORNECEDOR, P.UNI_MEDIDA, P.VALIDADE, P.ESTOQUE, P.VALOR, C.NOME AS "CATEGORIA"
FROM PRODUTOS P
INNER JOIN CATEGORIA C ON P.FK_CATEGORIA = C.ID_CATEGORIA
WHERE P.ID_PRODUTO = 5
ORDER BY ID


SELECT H.ID_HOSPEDAGEM, P.NOME, P.CPF, L.NOME AS LOCAL, H.STATUS, H.DATA_ENTRADA,H.HORA_ENTRADA, H.DATA_SAIDA, H.HORA_SAIDA, H.QUANT_PESSOAS
	FROM HOSPEDAGEM H
	INNER JOIN PESSOA P ON P.ID_PESSOA = H.FK_PESSOA
	INNER JOIN LOCAL L ON L.ID_LOCAL = H.FK_LOCAL


SELECT H.ID_HOSPEDAGEM, P.NOME, P.CPF, L.NOME_LOCAL AS LOCAL, H.STATUS, H.DATA_ENTRADA AS 'DATA ENTRADA',H.HORA_ENTRADA AS 'HORA ENTRADA', H.DATA_SAIDA AS 'DATA SAIDA', H.HORA_SAIDA AS 'HORA SAIDA', H.QUANT_PESSOAS AS  'PESSOAS'
	FROM HOSPEDAGEM H
	INNER JOIN PESSOA P ON P.ID_PESSOA = H.FK_PESSOA
	INNER JOIN LOCAL L ON L.ID_LOCAL = H.FK_LOCAL


exec sp_rename 'LOCAL.[NOME]', 'NOME_LOCAL', 'column'

-- QUERYS ADICIONADAS
exec sp_rename 'CATEGORIA.[NOME]', 'NOME_CATEGORIA', 'column'
exec sp_rename 'LOCAL.[NOME]', 'NOME_LOCAL', 'column'

CREATE OR ALTER TRIGGER TRG_CONTA_HOSPEDAGEM
ON DBO.HOSPEDAGEM
FOR INSERT AS
	DECLARE
		@IDHOSPEDAGEM INT, @IDLOCAL INT,  @VALOR FLOAT

	SELECT @IDHOSPEDAGEM = ID_HOSPEDAGEM FROM inserted
	SELECT @IDLOCAL = FK_LOCAL FROM inserted
	SET @VALOR = (SELECT VALOR FROM C_LOCAL WHERE ID_C_LOCAL = (SELECT FK_C_LOCAL FROM LOCAL WHERE ID_LOCAL = @IDLOCAL))

	INSERT INTO CONTAS VALUES ('PRIMEIRA CONTA',@VALOR, 'A', 'CONTA INICIAL', (SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOME_CATEGORIA = 'ENTRADA'), @IDHOSPEDAGEM )

GO


INSERT INTO USUARIO VALUES ('ADMIN', 'HOTEL1234', 13, 'ADMIN')
INSERT INTO USUARIO VALUES ('NIVEL1', 'HOTEL1234', 13, 'NIVEL1')
INSERT INTO USUARIO VALUES ('NIVEL2', 'HOTEL1234', 13, 'NIVEL2')
INSERT INTO USUARIO VALUES ('NIVEL3', 'HOTEL1234', 13, 'NIVEL3')

